### PR TITLE
AMP-99096 update snowflake documentation to add info about key pair

### PR DESCRIPTION
**Pull request by xiaowuc1**
# Amplitude Developer Docs PR

## Description

This PR adds documentation indicating the addition of key pair authentication for Snowflake import and export.

## Deadline

When do these changes need to be live on the site?
Ideally ASAP, as the feature is live now.

## Change type

- [] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [] Doc update.
- [X] New documentation.
- [] Non-documentation related fix or update.

# PR checklist:

- [X] My documentation follows the style guidelines of this project.
- [] I previewed my documentation on a local server using `mkdocs serve`.
- [] Running `mkdocs serve` didn't generate any failures.
- [X] I have performed a self-review of my own documentation.

@amplitude-dev-docs

### CODE REVIEW

**Comment by xiaowuc1** [comment]
image
Marking as draft for now since my markdown preview locally did not match what we see on live.

**Comment by xiaowuc1** [comment]
Screenshots of updated documentation.

image
image

**Comment by markzegarelli** [comment]
@xiaowuc1 Can you tell me more about the mismatch you see locally vs deployed?

**Comment by xiaowuc1** [comment]
> @xiaowuc1 Can you tell me more about the mismatch you see locally vs deployed?

I used a different markdown preview tool, after using `mkdocs serve` I saw the same thing locally as what was deployed to the AWS Amplify Console.

**Comment by markzegarelli** [comment]
> > @xiaowuc1 Can you tell me more about the mismatch you see locally vs deployed?
> 
> I used a different markdown preview tool, after using `mkdocs serve` I saw the same thing locally as what was deployed to the AWS Amplify Console.

Ah got it. I confirmed that the deployed rendered like it should, so I'll approve this.

**Review by markzegarelli — APPROVED** [review]

**Pull request merged**
