### PR TITLE
Amp 87688 sdk swift remove beta

### PR DESCRIPTION
**Pull request by justin-fiedler**
## Description
1. Remove Beta label form Swift SDK
2. Mark old iOS SDK as maintenance
3. Remove legacy iOS instructions from Quickstart page

* https://pr-48.d19s7xzcva2mw3.amplifyapp.com/data/sdks/ios-swift
* https://pr-48.d19s7xzcva2mw3.amplifyapp.com/data/sdks/ios
* https://pr-48.d19s7xzcva2mw3.amplifyapp.com/data/sdks/sdk-quickstart

## Change type
- [x] Doc update.

**Swift SDK**
image

**iOS SDK (old)**
image

**Quickstart**
image

### CODE REVIEW

**Comment by markzegarelli** [comment]
@justin-fiedler Can we add `(legacy)` or `(maintenance)` to the title of the old SDKs for better visibility?

**Comment by justin-fiedler** [comment]
> @justin-fiedler Can we add `(legacy)` or `(maintenance)` to the title of the old SDKs for better visibility?

Thanks @markzegarelli good catch. I renamed the old iOS page to "iOS SDK (Maintenance)".

**Review by markzegarelli — APPROVED** [review]

**Review by Mercy811 — APPROVED** [review]
Thank you Justin for updating the docs. Can't wait to see Swift GA🎉

**Review by falconandy — CHANGES_REQUESTED** [review]
1. Empty `Get Started` section for `iOS SDK (Maintenance)`:
image

2. `iOS Ampli Wrapper` page shows banner `Objective-C Not Supported`, Objective-C examples are not provided
image

3. `iOS SDK Migration Guide` still refers to `0.7` version
image

**Pull request merged**
