### PR TITLE
feat: AMP-94894 added Android session replay docs

### PR DESCRIPTION
**Pull request by justin-fiedler**
# Amplitude Developer Docs PR

## Description
Added Android session replay documentation for both `SessionReplayPlugin` and `SessionReplay` standalone SDK.

* Usage
* Limitations
* Troubleshooting
* Direct links only (intentionally not included in nav as an Alpha)

## Links

* https://pr-221.d19s7xzcva2mw3.amplifyapp.com/session-replay/sdks/standalone-android
* https://pr-221.d19s7xzcva2mw3.amplifyapp.com/session-replay/sdks/plugin-android

## Deadline
March 8

## Change type

- [x] New documentation.

# PR checklist:

- [x] My documentation follows the style guidelines of this project.
- [x] I previewed my documentation on a local server using `mkdocs serve`.
- [x] Running `mkdocs serve` didn't generate any failures.
- [x] I have performed a self-review of my own documentation.

@amplitude-dev-docs

### CODE REVIEW

**Comment by katie-amplitude** [comment]
These are looking great.

Plug-in

1. typo says "lastest" instead of "latest" https://pr-221.d19s7xzcva2mw3.amplifyapp.com/session-replay/sdks/plugin-android/#quickstart

2. On the section about Capturing, is this sentence actually true with the Android SDK?  https://pr-221.d19s7xzcva2mw3.amplifyapp.com/session-replay/sdks/plugin-android/#captured-sessions-contain-limited-information

_This means you can't use tools like Funnel, Segmentation, or Journeys charts to find session replays. You can find session replays with the User Sessions chart or through User Lookup._

3. In this part about session replay not capturing Session Replay ID - should it say "Browser SDK"? https://pr-221.d19s7xzcva2mw3.amplifyapp.com/session-replay/sdks/plugin-android/#some-sessions-dont-include-the-session-replay-id-property

_If you instrument an event with a source different from the source you connect to Session Replay. For example, your application may send events from a backend source, rather than the Browser SDK._

Stand-Alone

4. On the Standalone SDK it references the plug-in - is that correct?  https://pr-221.d19s7xzcva2mw3.amplifyapp.com/session-replay/sdks/standalone-android/

_Use the latest version of the Session Replay Plugin above version 0.4.1. For a list of available versions, see the [release versions](https://central.sonatype.com/artifact/com.amplitude/session-replay-android/versions) on Maven Central._

5.  https://pr-221.d19s7xzcva2mw3.amplifyapp.com/session-replay/sdks/standalone-android/#known-limitations references a bullet on the plug-in - should be removed?

_When using the plugin, session events must be enabled on the SDK. Learn more in [Tracking default sessions events](https://pr-221.d19s7xzcva2mw3.amplifyapp.com/session-replay/sdks/standalone-android/#track-default-session-events)._

**Comment by justin-fiedler** [comment]
> These are looking great.

Thanks @katie-amplitude

1. Fixed
2. I think this is accurate, afaik this has to due with the backend not the SDK so should be the same across platforms.
3. Updated for Android
4. Fixed
5. Fixed. This is a shared section, I updated to only show the Plugin info on the Plugin page.

**Review by katie-amplitude — APPROVED** [review]
great

**Review by kickerbear — APPROVED** [review]
LGTM

**Pull request merged**
