### PR TITLE
Create blueshift-cohort.md

### PR DESCRIPTION
**Pull request by Brandoncharleskhoo1**
# Amplitude Developer Docs PR

## Description

Describe your changes. 

## Deadline

When do these changes need to be live on the site?

## Change type

- [ ] Doc bug fix. Fixes #[insert issue number]. Amplitude contributors include Jira issue number. 
- [ ] Doc update.
- [ ] New documentation.
- [ ] Non-documentation related fix or update.

# PR checklist:

- [ ] My documentation follows the style guidelines of this project.
- [ ] I previewed my documentation on a local server using `mkdocs serve`.
- [ ] Running `mkdocs serve` didn't generate any failures.
- [ ] I have performed a self-review of my own documentation.

@amplitude-dev-docs

### CODE REVIEW

**Comment by Brandoncharleskhoo1** [comment]
Screenshot 2024-04-23 at 5 21 21 PM
@markzegarelli I don't get what i have to fix with this Vale error.

**Comment by markzegarelli** [comment]
> Screenshot 2024-04-23 at 5 21 21 PM @markzegarelli I don't get what i have to fix with this Vale error.

That's a weird one, you can ignore it.

**Review by markzegarelli — APPROVED** [review]

**Comment by Brandoncharleskhoo1** [comment]
@markzegarelli i don't know how to get rid of the conflicting files. Happy to shadow you for a few mins to learn on this

**Comment by markzegarelli** [comment]
> @markzegarelli i don't know how to get rid of the conflicting files. Happy to shadow you for a few mins to learn on this

Fixed! This one was pretty simple, just an issue of accept.txt having more recent changes than when you created the branch. Essentially you were trying to put a term on a line that had another change, so it conflicted. Ping me next time it happens and we can walk through it, or I'll record a loom.

**Comment by Brandoncharleskhoo1** [comment]
> > @markzegarelli i don't know how to get rid of the conflicting files. Happy to shadow you for a few mins to learn on this
> 
> Fixed! This one was pretty simple, just an issue of accept.txt having more recent changes than when you created the branch. Essentially you were trying to put a term on a line that had another change, so it conflicted. Ping me next time it happens and we can walk through it, or I'll record a loom.

**Comment by Brandoncharleskhoo1** [comment]
> > > @markzegarelli i don't know how to get rid of the conflicting files. Happy to shadow you for a few mins to learn on this
> > 
> > 
> > Fixed! This one was pretty simple, just an issue of accept.txt having more recent changes than when you created the branch. Essentially you were trying to put a term on a line that had another change, so it conflicted. Ping me next time it happens and we can walk through it, or I'll record a loom.

Awesome! Thanks Mark! I'll probs need a loom video or i'll ping you next time it happens on this haha

**Pull request merged**
